Triggers update & Job scheduler
ForloopAI/forloop_modules pull request #17
Opened 2023-11-02 16:56 UTC by ZaiZu2

Dependencies:
- [https://github.com/ForloopAI/forloop_platform/pull/781](https://github.com/ForloopAI/forloop_platform/pull/781)
- [https://github.com/ForloopAI/forloop_common_structures/pull/4](https://github.com/ForloopAI/forloop_common_structures/pull/4)

Introduces:
- Updated/cleaned up Trigger dataclass/APIschema/DBmodel

2023-11-09 14:49 UTC, DovaX requested changes

2023-11-09 14:49 UTC, DovaX commented on forloop_modules/queries/db_model_templates.py
> +from forloop_common_structures.core.trigger import TriggerFrequencyEnum
Wrong dependency 
![obrazek](https://github.com/ForloopAI/forloop_modules/assets/29150831/b5e912c8-c06c-4e43-a800-15305740d0a0)

2023-11-09 14:49 UTC, DovaX commented on forloop_modules/queries/db_model_templates.py
> +#     first_run: datetime.datetime
first_run_datetime or first_run_utc is better

2023-11-11 13:30 UTC, YoungMasterGandalf approved these changes

2023-11-13 13:45 UTC, DovaX approved these changes

2023-11-13 13:46 UTC, merged