Daniel to dev
ForloopAI/forloop_modules pull request #36
Opened 2024-01-04 14:09 UTC by YoungMasterGandalf

2024-01-04 23:36 UTC, DovaX requested changes
I dont understand where you backed up the code for reading of the jupyter notebook :D I didnt want you to deprecate it 👍 
+ also it creates scripts, but where is a node to run script?

2024-01-05 19:47 UTC, YoungMasterGandalf commented
> I dont understand where you backed up the code for reading of the jupyter notebook :D I didnt want you to deprecate it 👍
> 
> * also it creates scripts, but where is a node to run script?

Do you mean the commented one, the "try - except - finally" part? I thought it was obsolete so I didn't back it up :D

2024-01-05 19:48 UTC, YoungMasterGandalf commented
> I dont understand where you backed up the code for reading of the jupyter notebook :D I didnt want you to deprecate it 👍
> 
> * also it creates scripts, but where is a node to run script?

I didn't finish the running scripts part yet. The DB tasks seemed like a greater priority so I wanted to push this, go to them and return to running scripts @DovaX

2024-01-21 14:05 UTC, DovaX approved these changes

2024-01-21 14:05 UTC, DovaX commented on forloop_modules/queries/db_model_templates.py
> +    node_uid: str = ""
node_uid = "0" is maybe better? -> then, if 0 is passed anywhere - it means you didnt specify it where you should do that :)

2024-01-21 14:30 UTC, merged